-- AlterTable
ALTER TABLE `Item` ADD COLUMN `itemType` ENUM('SWORD', 'AXE', 'BOW', 'CROSSBOW', 'STAFF', 'WAND', 'DAGGER', 'MACE', 'SPEAR', 'FLAIL', 'HELMET', 'CHESTPLATE', 'LEGGINGS', 'BOOTS', 'GLOVES', 'SHOULDERS', 'BELT', 'RING', 'AMULET', 'NECKLACE', 'BACKPACK', 'ORE', 'LOG', 'HERB', 'FISH', 'HIDE', 'STONE', 'GEM', 'POTION', 'FOOD', 'ELIXIR', 'SCROLL', 'MATERIAL', 'INGREDIENT', 'RECIPE', 'QUEST_ITEM', 'KEY', 'CURRENCY', 'PET', 'MOUNT', 'OTHER') NULL,
    ADD COLUMN `maxStackSize` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `stackable` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `UserItem` ADD COLUMN `quantity` INTEGER NOT NULL DEFAULT 1;
