// next-env.d.ts carries Next's ambient module declarations for image imports,
// but it is gitignored and only regenerated by running `next`. CI therefore
// typechecked without it and failed on the one `import … from "*.png"` in the
// tree. This committed reference makes `tsc --noEmit` reproducible anywhere.
/// <reference types="next/image-types/global" />
