-- CreateTable
CREATE TABLE `ItemStatProgression` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `itemId` INTEGER NOT NULL,
    `statType` ENUM('PHYSICAL_DAMAGE_MIN', 'PHYSICAL_DAMAGE_MAX', 'MAGIC_DAMAGE_MIN', 'MAGIC_DAMAGE_MAX', 'CRITICAL_CHANCE', 'CRITICAL_DAMAGE', 'ATTACK_SPEED', 'ACCURACY', 'ARMOR', 'MAGIC_RESIST', 'EVASION_MELEE', 'EVASION_RANGED', 'EVASION_MAGIC', 'BLOCK_CHANCE', 'FIRE_RESIST', 'COLD_RESIST', 'LIGHTNING_RESIST', 'POISON_RESIST', 'HEALTH', 'MANA', 'HEALTH_REGEN', 'MANA_REGEN', 'PRAYER_POINTS', 'MOVEMENT_SPEED', 'LUCK', 'GOLD_FIND', 'EXPERIENCE_GAIN', 'LIFESTEAL', 'THORNS') NOT NULL,
    `baseValue` DOUBLE NOT NULL,
    `unlocksAtRarity` ENUM('WORTHLESS', 'BROKEN', 'COMMON', 'UNCOMMON', 'RARE', 'EXQUISITE', 'EPIC', 'ELITE', 'UNIQUE', 'LEGENDARY', 'MYTHIC', 'DIVINE') NOT NULL,

    INDEX `ItemStatProgression_itemId_unlocksAtRarity_idx`(`itemId`, `unlocksAtRarity`),
    UNIQUE INDEX `ItemStatProgression_itemId_statType_key`(`itemId`, `statType`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ItemStatProgression` ADD CONSTRAINT `ItemStatProgression_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `Item`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
