-- CreateTable
CREATE TABLE `CombatConfig` (
    `id` INTEGER NOT NULL DEFAULT 1,
    `armorK0` DOUBLE NOT NULL DEFAULT 50,
    `armorK1` DOUBLE NOT NULL DEFAULT 3,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
