-- AlterTable
ALTER TABLE `CharacterBaseStat` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX','CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST','EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE','FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST','HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED','LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY','WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY') NOT NULL;

-- AlterTable
ALTER TABLE `ItemStat` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX','CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST','EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE','FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST','HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED','LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY','WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY') NOT NULL;

-- AlterTable
ALTER TABLE `ItemStatProgression` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX','CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST','EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE','FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST','HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED','LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY','WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY') NOT NULL;

-- AlterTable
ALTER TABLE `UserItemStat` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX','CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST','EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE','FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST','HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED','LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY','WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY') NOT NULL;

-- CreateTable
CREATE TABLE `ToolEfficiency` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `itemId` INTEGER NOT NULL,
    `actionType` ENUM('WOODCUTTING','MINING','FISHING','GATHERING','ALCHEMY','SMELTING','COOKING','FORGE') NOT NULL,
    `baseEfficiency` DOUBLE NOT NULL,

    INDEX `ToolEfficiency_actionType_idx`(`actionType`),
    UNIQUE INDEX `ToolEfficiency_itemId_actionType_key`(`itemId`, `actionType`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ToolEfficiency` ADD CONSTRAINT `ToolEfficiency_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `Item`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
