-- AlterTable
ALTER TABLE `Item` MODIFY `rarity` ENUM('WORTHLESS', 'BROKEN', 'COMMON', 'UNCOMMON', 'RARE', 'EXQUISITE', 'EPIC', 'ELITE', 'UNIQUE', 'LEGENDARY', 'MYTHIC', 'DIVINE') NOT NULL DEFAULT 'COMMON';

-- AlterTable
ALTER TABLE `RarityConfig` MODIFY `rarity` ENUM('WORTHLESS', 'BROKEN', 'COMMON', 'UNCOMMON', 'RARE', 'EXQUISITE', 'EPIC', 'ELITE', 'UNIQUE', 'LEGENDARY', 'MYTHIC', 'DIVINE') NOT NULL,
    MODIFY `nextRarity` ENUM('WORTHLESS', 'BROKEN', 'COMMON', 'UNCOMMON', 'RARE', 'EXQUISITE', 'EPIC', 'ELITE', 'UNIQUE', 'LEGENDARY', 'MYTHIC', 'DIVINE') NULL;

-- AlterTable
ALTER TABLE `UserItem` MODIFY `rarity` ENUM('WORTHLESS', 'BROKEN', 'COMMON', 'UNCOMMON', 'RARE', 'EXQUISITE', 'EPIC', 'ELITE', 'UNIQUE', 'LEGENDARY', 'MYTHIC', 'DIVINE') NOT NULL DEFAULT 'COMMON';
