-- AlterTable
ALTER TABLE `CharacterBaseStat` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN', 'PHYSICAL_DAMAGE_MAX', 'MAGIC_DAMAGE_MIN', 'MAGIC_DAMAGE_MAX', 'CRITICAL_CHANCE', 'CRITICAL_DAMAGE', 'ATTACK_SPEED', 'ACCURACY', 'ARMOR', 'MAGIC_RESIST', 'EVASION_MELEE', 'EVASION_RANGED', 'EVASION_MAGIC', 'BLOCK_CHANCE', 'FIRE_RESIST', 'COLD_RESIST', 'LIGHTNING_RESIST', 'POISON_RESIST', 'HEALTH', 'MANA', 'HEALTH_REGEN', 'MANA_REGEN', 'PRAYER_POINTS', 'MOVEMENT_SPEED', 'LUCK', 'GOLD_FIND', 'EXPERIENCE_GAIN', 'LIFESTEAL', 'THORNS', 'CARRYING_CAPACITY') NOT NULL;

-- AlterTable
ALTER TABLE `Inventory` MODIFY `maxSlots` INTEGER NOT NULL DEFAULT 25;

-- AlterTable
ALTER TABLE `ItemStat` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN', 'PHYSICAL_DAMAGE_MAX', 'MAGIC_DAMAGE_MIN', 'MAGIC_DAMAGE_MAX', 'CRITICAL_CHANCE', 'CRITICAL_DAMAGE', 'ATTACK_SPEED', 'ACCURACY', 'ARMOR', 'MAGIC_RESIST', 'EVASION_MELEE', 'EVASION_RANGED', 'EVASION_MAGIC', 'BLOCK_CHANCE', 'FIRE_RESIST', 'COLD_RESIST', 'LIGHTNING_RESIST', 'POISON_RESIST', 'HEALTH', 'MANA', 'HEALTH_REGEN', 'MANA_REGEN', 'PRAYER_POINTS', 'MOVEMENT_SPEED', 'LUCK', 'GOLD_FIND', 'EXPERIENCE_GAIN', 'LIFESTEAL', 'THORNS', 'CARRYING_CAPACITY') NOT NULL;

-- AlterTable
ALTER TABLE `ItemStatProgression` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN', 'PHYSICAL_DAMAGE_MAX', 'MAGIC_DAMAGE_MIN', 'MAGIC_DAMAGE_MAX', 'CRITICAL_CHANCE', 'CRITICAL_DAMAGE', 'ATTACK_SPEED', 'ACCURACY', 'ARMOR', 'MAGIC_RESIST', 'EVASION_MELEE', 'EVASION_RANGED', 'EVASION_MAGIC', 'BLOCK_CHANCE', 'FIRE_RESIST', 'COLD_RESIST', 'LIGHTNING_RESIST', 'POISON_RESIST', 'HEALTH', 'MANA', 'HEALTH_REGEN', 'MANA_REGEN', 'PRAYER_POINTS', 'MOVEMENT_SPEED', 'LUCK', 'GOLD_FIND', 'EXPERIENCE_GAIN', 'LIFESTEAL', 'THORNS', 'CARRYING_CAPACITY') NOT NULL;

-- AlterTable
ALTER TABLE `UserItemStat` MODIFY `statType` ENUM('PHYSICAL_DAMAGE_MIN', 'PHYSICAL_DAMAGE_MAX', 'MAGIC_DAMAGE_MIN', 'MAGIC_DAMAGE_MAX', 'CRITICAL_CHANCE', 'CRITICAL_DAMAGE', 'ATTACK_SPEED', 'ACCURACY', 'ARMOR', 'MAGIC_RESIST', 'EVASION_MELEE', 'EVASION_RANGED', 'EVASION_MAGIC', 'BLOCK_CHANCE', 'FIRE_RESIST', 'COLD_RESIST', 'LIGHTNING_RESIST', 'POISON_RESIST', 'HEALTH', 'MANA', 'HEALTH_REGEN', 'MANA_REGEN', 'PRAYER_POINTS', 'MOVEMENT_SPEED', 'LUCK', 'GOLD_FIND', 'EXPERIENCE_GAIN', 'LIFESTEAL', 'THORNS', 'CARRYING_CAPACITY') NOT NULL;
