-- Hunting is the first creature-facing PvE activity. Creature/drop tables are
-- deliberately shared so future dungeon monsters can use the same catalogue.

ALTER TABLE `ToolEfficiency` MODIFY `actionType` ENUM(
  'WOODCUTTING','MINING','FISHING','GARDENING','GATHERING','HUNTING','ALCHEMY',
  'BLACKSMITHING','WEAPONSMITHING','CARPENTRY','COOKING','TAILORING','FORGE'
) NOT NULL;

ALTER TABLE `VocationalResource` MODIFY `actionType` ENUM(
  'WOODCUTTING','MINING','FISHING','GARDENING','GATHERING','HUNTING','ALCHEMY',
  'BLACKSMITHING','WEAPONSMITHING','CARPENTRY','COOKING','TAILORING','FORGE'
) NOT NULL;

ALTER TABLE `UserVocationalActivity` MODIFY `actionType` ENUM(
  'WOODCUTTING','MINING','FISHING','GARDENING','GATHERING','HUNTING','ALCHEMY',
  'BLACKSMITHING','WEAPONSMITHING','CARPENTRY','COOKING','TAILORING','FORGE'
) NOT NULL;

ALTER TABLE `XpMultiplier` MODIFY `vocationalActionType` ENUM(
  'WOODCUTTING','MINING','FISHING','GARDENING','GATHERING','HUNTING','ALCHEMY',
  'BLACKSMITHING','WEAPONSMITHING','CARPENTRY','COOKING','TAILORING','FORGE'
) NULL;

ALTER TABLE `XpTransaction` MODIFY `vocationalActionType` ENUM(
  'WOODCUTTING','MINING','FISHING','GARDENING','GATHERING','HUNTING','ALCHEMY',
  'BLACKSMITHING','WEAPONSMITHING','CARPENTRY','COOKING','TAILORING','FORGE'
) NULL;

ALTER TABLE `CharacterBaseStat` MODIFY `statType` ENUM(
  'PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX',
  'CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST',
  'EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE',
  'FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST',
  'HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED',
  'LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY',
  'WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY',
  'GATHERING_EFFICIENCY','HUNTING_EFFICIENCY'
) NOT NULL;

ALTER TABLE `ItemStat` MODIFY `statType` ENUM(
  'PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX',
  'CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST',
  'EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE',
  'FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST',
  'HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED',
  'LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY',
  'WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY',
  'GATHERING_EFFICIENCY','HUNTING_EFFICIENCY'
) NOT NULL;

ALTER TABLE `ItemStatProgression` MODIFY `statType` ENUM(
  'PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX',
  'CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST',
  'EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE',
  'FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST',
  'HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED',
  'LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY',
  'WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY',
  'GATHERING_EFFICIENCY','HUNTING_EFFICIENCY'
) NOT NULL;

ALTER TABLE `UserItemStat` MODIFY `statType` ENUM(
  'PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX',
  'CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST',
  'EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE',
  'FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST',
  'HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED',
  'LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY',
  'WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY',
  'GATHERING_EFFICIENCY','HUNTING_EFFICIENCY'
) NOT NULL;

ALTER TABLE `FoodEffectStat` MODIFY `statType` ENUM(
  'PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX',
  'CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST',
  'EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE',
  'FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST',
  'HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED',
  'LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY',
  'WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY',
  'GATHERING_EFFICIENCY','HUNTING_EFFICIENCY'
) NOT NULL;

ALTER TABLE `ItemStatRarityOverride` MODIFY `statType` ENUM(
  'PHYSICAL_DAMAGE_MIN','PHYSICAL_DAMAGE_MAX','MAGIC_DAMAGE_MIN','MAGIC_DAMAGE_MAX',
  'CRITICAL_CHANCE','CRITICAL_DAMAGE','ATTACK_SPEED','ACCURACY','ARMOR','MAGIC_RESIST',
  'EVASION_MELEE','EVASION_RANGED','EVASION_MAGIC','BLOCK_CHANCE',
  'FIRE_RESIST','COLD_RESIST','LIGHTNING_RESIST','POISON_RESIST',
  'HEALTH','MANA','HEALTH_REGEN','MANA_REGEN','PRAYER_POINTS','MOVEMENT_SPEED',
  'LUCK','GOLD_FIND','EXPERIENCE_GAIN','LIFESTEAL','THORNS','CARRYING_CAPACITY',
  'WOODCUTTING_EFFICIENCY','MINING_EFFICIENCY','FISHING_EFFICIENCY',
  'GATHERING_EFFICIENCY','HUNTING_EFFICIENCY'
) NOT NULL;

CREATE TABLE `Creature` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `kind` ENUM('ANIMAL','MONSTER') NOT NULL DEFAULT 'ANIMAL',
  `asset` VARCHAR(191) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `attackStyle` ENUM('MELEE','RANGED','MAGIC') NOT NULL DEFAULT 'MELEE',
  `attackChance` DOUBLE NOT NULL DEFAULT 0,
  `damageMin` INTEGER NOT NULL DEFAULT 0,
  `damageMax` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `Creature_name_key`(`name`),
  INDEX `Creature_kind_enabled_idx`(`kind`, `enabled`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CreatureDrop` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `creatureId` INTEGER NOT NULL,
  `itemId` INTEGER NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `baseChance` DOUBLE NOT NULL DEFAULT 0.5,
  `minQuantity` INTEGER NOT NULL DEFAULT 1,
  `maxQuantity` INTEGER NOT NULL DEFAULT 1,
  `requiredLevel` INTEGER NOT NULL DEFAULT 1,
  UNIQUE INDEX `CreatureDrop_creatureId_itemId_key`(`creatureId`, `itemId`),
  INDEX `CreatureDrop_creatureId_enabled_idx`(`creatureId`, `enabled`),
  INDEX `CreatureDrop_itemId_idx`(`itemId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `HuntingGround` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `locationId` INTEGER NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `requiredHuntingLevel` INTEGER NOT NULL DEFAULT 1,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `accidentChance` DOUBLE NOT NULL DEFAULT 0,
  `accidentDamageMin` INTEGER NOT NULL DEFAULT 0,
  `accidentDamageMax` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `HuntingGround_locationId_name_key`(`locationId`, `name`),
  INDEX `HuntingGround_locationId_enabled_sortOrder_idx`(`locationId`, `enabled`, `sortOrder`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `HuntingGroundCreature` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `groundId` INTEGER NOT NULL,
  `creatureId` INTEGER NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `encounterWeight` DOUBLE NOT NULL DEFAULT 1,
  UNIQUE INDEX `HuntingGroundCreature_groundId_creatureId_key`(`groundId`, `creatureId`),
  INDEX `HuntingGroundCreature_groundId_enabled_idx`(`groundId`, `enabled`),
  INDEX `HuntingGroundCreature_creatureId_idx`(`creatureId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `HuntingDuration` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(191) NOT NULL,
  `durationSeconds` INTEGER NOT NULL,
  `encounterRolls` INTEGER NOT NULL DEFAULT 2,
  `quantityMultiplier` DOUBLE NOT NULL DEFAULT 1,
  `dangerMultiplier` DOUBLE NOT NULL DEFAULT 1,
  `xpReward` INTEGER NOT NULL DEFAULT 0,
  `requiredHuntingLevel` INTEGER NOT NULL DEFAULT 1,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `HuntingDuration_label_key`(`label`),
  UNIQUE INDEX `HuntingDuration_durationSeconds_key`(`durationSeconds`),
  INDEX `HuntingDuration_enabled_sortOrder_idx`(`enabled`, `sortOrder`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `HuntingConfig` (
  `id` INTEGER NOT NULL DEFAULT 1,
  `damageEnabled` BOOLEAN NOT NULL DEFAULT true,
  `globalDangerMultiplier` DOUBLE NOT NULL DEFAULT 1,
  `maxHealthLossPercent` DOUBLE NOT NULL DEFAULT 30,
  `minimumRemainingHealthPercent` DOUBLE NOT NULL DEFAULT 5,
  `minimumHealthToStartPercent` DOUBLE NOT NULL DEFAULT 25,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `UserHuntingExpedition` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(191) NOT NULL,
  `groundId` INTEGER NOT NULL,
  `durationId` INTEGER NULL,
  `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `endsAt` DATETIME(3) NOT NULL,
  `claimedAt` DATETIME(3) NULL,
  `durationSeconds` INTEGER NOT NULL,
  `encounterRolls` INTEGER NOT NULL,
  `quantityMultiplier` DOUBLE NOT NULL,
  `dangerMultiplier` DOUBLE NOT NULL,
  `xpReward` INTEGER NOT NULL,
  `skillLevelSnapshot` INTEGER NOT NULL,
  `luckSnapshot` DOUBLE NOT NULL,
  `huntingEfficiencySnapshot` DOUBLE NOT NULL,
  `armorSnapshot` DOUBLE NOT NULL,
  `magicResistSnapshot` DOUBLE NOT NULL,
  `evasionMeleeSnapshot` DOUBLE NOT NULL,
  `evasionRangedSnapshot` DOUBLE NOT NULL,
  `evasionMagicSnapshot` DOUBLE NOT NULL,
  `blockChanceSnapshot` DOUBLE NOT NULL,
  `movementSpeedSnapshot` DOUBLE NOT NULL,
  `maxHealthSnapshot` DOUBLE NOT NULL,
  `resolutionSeed` VARCHAR(191) NOT NULL,
  `creaturePool` JSON NOT NULL,
  `riskConfig` JSON NOT NULL,
  `rewards` JSON NULL,
  `report` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `UserHuntingExpedition_userId_key`(`userId`),
  INDEX `UserHuntingExpedition_endsAt_idx`(`endsAt`),
  INDEX `UserHuntingExpedition_groundId_idx`(`groundId`),
  INDEX `UserHuntingExpedition_durationId_idx`(`durationId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CharacterHealth` (
  `userId` VARCHAR(191) NOT NULL,
  `currentHealth` DOUBLE NOT NULL,
  `regeneratedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `CharacterHealth_regeneratedAt_idx`(`regeneratedAt`),
  PRIMARY KEY (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `CreatureDrop`
  ADD CONSTRAINT `CreatureDrop_creatureId_fkey` FOREIGN KEY (`creatureId`) REFERENCES `Creature`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `CreatureDrop_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `Item`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `HuntingGround`
  ADD CONSTRAINT `HuntingGround_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `Location`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `HuntingGroundCreature`
  ADD CONSTRAINT `HuntingGroundCreature_groundId_fkey` FOREIGN KEY (`groundId`) REFERENCES `HuntingGround`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `HuntingGroundCreature_creatureId_fkey` FOREIGN KEY (`creatureId`) REFERENCES `Creature`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `UserHuntingExpedition`
  ADD CONSTRAINT `UserHuntingExpedition_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `UserHuntingExpedition_groundId_fkey` FOREIGN KEY (`groundId`) REFERENCES `HuntingGround`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `UserHuntingExpedition_durationId_fkey` FOREIGN KEY (`durationId`) REFERENCES `HuntingDuration`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `CharacterHealth`
  ADD CONSTRAINT `CharacterHealth_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO `HuntingConfig`
  (`id`, `damageEnabled`, `globalDangerMultiplier`, `maxHealthLossPercent`, `minimumRemainingHealthPercent`, `minimumHealthToStartPercent`, `createdAt`, `updatedAt`)
VALUES (1, true, 1, 30, 5, 25, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`);

INSERT INTO `skills` (`skill_name`, `description`, `category`)
VALUES ('Hunting', 'Track animals through local hunting grounds and return with meat, hides, bones, and other materials.', 'VOCATION')
ON DUPLICATE KEY UPDATE
  `description` = VALUES(`description`),
  `category` = VALUES(`category`);
